### ISSUE TITLE
The Configs to Achieve The Best Performance

### ISSUE THREAD

**Issue by canqin001** [gospodima/Extended-SimGNN#3]
Hi,

Did you try different configs on these datasets? I am curious what are the best configs on different datasets.

Thanks.

**Comment by gospodima** [comment]
Hi @canqin001,
sorry for the late response. I tried different configs but I wouldn't be sure about best performance since I was restricted in time and therefore the learning time was not long enough to achieve a maximum performance for each config. 
The most important points that I can mention: for my experiments on LINUX and AIDS datasets the Graph Isomorphism Operator gave better performance than the GCN. However, the overfitting effect was also higher and on a longer learning period probably some play with dropout will be required. Also, usage of histogram (pairwise node comparison) caused a significant overfitting effect, so usually I turned it off. 
Regarding other parameters I can't say much unfortunately.
